language: python 
# install: 
#         - pip install Flask
#         - pip install Flask_Cors
#         - pip install requests
#         - pip install seaborn
#         - pip install numpy
#         - pip install matplotlib

script: 
        python test.py